In [1]:
import pandas as pd

df = pd.read_sql(
    """SELECT * FROM "feed_action" LIMIT 10 """,
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

df.head()

   user_id  post_id action                time        id
0    87074     6475   view 2022-01-15 19:04:38  42009857
1    95394     6413   like 2022-01-15 19:04:38  42009858
2    95394     6337   like 2022-01-15 19:04:38  42009859
3    89590     6316   view 2022-01-15 19:04:38  42009860
4     4319     6349   view 2022-01-15 19:04:38  42009861

In [2]:
con_url = con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml"

In [3]:
con_url = con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml"

df = pd.read_sql(
    '''
    SELECT * FROM "user"
''',
    con=con_url
)

df

,id,gender,age,country,city,exp_group,os,source
0,200,1,34,Russia,Degtyarsk,3,Android,ads
1,201,0,37,Russia,Abakan,0,Android,ads
2,202,1,17,Russia,Smolensk,4,Android,ads
3,203,0,18,Russia,Moscow,1,iOS,ads
4,204,0,36,Russia,Anzhero-Sudzhensk,3,Android,ads
...,...,...,...,...,...,...,...,...
163200,168548,0,36,Russia,Kaliningrad,4,Android,organic
163201,168549,0,18,Russia,Tula,2,Android,organic
163202,168550,1,41,Russia,Yekaterinburg,4,Android,organic
163203,168551,0,38,Russia,Moscow,3,iOS,organic
163204,168552,1,16,Russia,Ivanteyevka,4,Android,organic

In [4]:
import psycopg2

In [5]:
connection = psycopg2.connect(
    database="startml",
    user="robot-startml-ro",
    password="pheiph0hahj1Vaif",
    host="postgres.lab.karpov.courses",
    port=6432
)

cursor = connection.cursor()

In [6]:
cursor.execute('''
SELECT DISTINCT topic
FROM post;
''')

results = cursor.fetchall()
results

[('tech',),
 ('covid',),
 ('movie',),
 ('entertainment',),
 ('politics',),
 ('sport',),
 ('business',)]

In [7]:
cursor.execute('''
SELECT id, city
FROM "user"
WHERE age > 30 AND os = 'iOS'
''')

results = cursor.fetchall()
results

# cursor.close()
# connection.close()

[(212, 'Podolsk'),
 (222, 'Ulyanovsk'),
 (224, 'Yekaterinburg'),
 (226, 'Moscow'),
 (243, 'Ekibastuz'),
 (247, 'Saint Petersburg'),
 (255, 'Saint Petersburg'),
 (256, 'Shakhty'),
 (258, 'Baku'),
 (267, 'Pyatigorsk'),
 (269, 'Moscow'),
 (276, 'Asipovichy'),
 (281, 'Beloyarskiy'),
 (315, 'Krasnoyarsk'),
 (318, 'Moscow'),
 (325, 'Ufa'),
 (330, 'Tver'),
 (338, 'Astrakhan'),
 (364, 'Homyel’'),
 (370, 'Balashov'),
 (382, 'Kstovo'),
 (404, 'Blagoveshchensk'),
 (444, 'Tomsk'),
 (456, 'Mikhaylovka'),
 (477, 'Chelyabinsk'),
 (480, 'Velykyi Bychkiv'),
 (498, 'Bol’shoye Boldino'),
 (503, 'Atyraū'),
 (509, 'Noginsk'),
 (514, 'Ivanovo'),
 (515, 'Gubkin'),
 (520, 'Tyumen'),
 (529, 'Nizhniy Novgorod'),
 (547, 'Moscow'),
 (557, 'Neftekamsk'),
 (561, 'Sochi'),
 (566, 'Chapayevsk'),
 (572, 'Melitopol'),
 (597, 'Uglich'),
 (599, 'Saint Petersburg'),
 (600, 'Moscow'),
 (601, 'Moscow'),
 (604, 'Ufa'),
 (608, 'Leninsk-Kuznetskiy'),
 (614, 'Nizhnevartovsk'),
 (616, 'Moscow'),
 (623, 'Arsenyev'),
 (629, 'Ivanteyevka'),
 (641, 'Staryy Oskol'),
 (686, 'Naberezhnyye Chelny'),
 (691, 'Davlekanovo'),
 (694, 'Moscow'),
 (696, 'Khabarovsk'),
 (717, 'Balakovo'),
 (729, 'Saratov'),
 (741, 'Homyel’'),
 (759, 'Krasnodar'),
 (783, 'Neftekamsk'),
 (788, 'Kyiv'),
 (795, 'Sumy'),
 (803, 'Kostroma'),
 (822, 'Ishimbay'),
 (837, 'Yakhroma'),
 (847, 'Kropotkin'),
 (848, 'Riga'),
 (856, 'Almaty'),
 (858, 'Yekaterinburg'),
 (859, 'Chekhov'),
 (861, 'Omsk'),
 (863, 'Tolyatti'),
 (866, 'Petrozavodsk'),
 (884, 'Kuvandyk'),
 (900, 'Moscow'),
 (902, 'Armizonskoye'),
 (923, 'Shaami-Yurt'),
 (930, 'Novosibirsk'),
 (936, 'Moscow'),
 (941, 'Chelyabinsk'),
 (942, 'Nur-Sultan'),
 (947, 'Orenburg'),
 (959, 'Baku'),
 (961, 'Moscow'),
 (962, 'Kursk'),
 (1006, 'Volgograd'),
 (1012, 'Domodedovo'),
 (1013, 'Malgobek'),
 (1016, 'Svetlyy'),
 (1018, 'Smila'),
 (1019, 'Bryansk'),
 (1022, 'Chelyabinsk'),
 (1026, 'Saint Petersburg'),
 (1031, 'Berezniki'),
 (1034, 'Novoshakhtinsk'),
 (1046, 'Penza'),
 (1053, 'Lensk'),
 (1055, 'Saint Petersburg'),
 (1075, 'Orsk'),
 (1086, 'Magadan'),
 (1113, 'Noginsk'),
 (1116, 'Moscow'),
 (1130, 'Ulyanovsk'),
 (1140, 'Chelyabinsk'),
 (1148, 'Yekaterinburg'),
 (1158, 'Kirov'),
 (1188, 'Moscow'),
 (1192, 'Severodvinsk'),
 (1204, 'Novosibirsk'),
 (1214, 'Opfikon'),
 (1217, 'Oktyabr’skiy'),
 (1219, 'Kherson'),
 (1222, 'Zarinsk'),
 (1231, 'Belokurikha'),
 (1256, 'Krymsk'),
 (1274, 'Kyiv'),
 (1280, 'Perm'),
 (1289, 'Zheleznogorsk'),
 (1295, 'Yelabuga'),
 (1297, 'Syktyvkar'),
 (1299, 'Akhremawtsy'),
 (1309, 'Petrozavodsk'),
 (1311, 'Brest'),
 (1318, 'Kryvyi Rih'),
 (1327, 'Novokuznetsk'),
 (1340, 'Kazan'),
 (1362, 'Monchegorsk'),
 (1373, 'Ulyanovsk'),
 (1390, 'Moscow'),
 (1402, 'Oulu'),
 (1414, 'Magadan'),
 (1415, 'Petropavlovsk-Kamchatskiy'),
 (1421, 'Tolyatti'),
 (1435, 'Kovrov'),
 (1439, 'Saint Petersburg'),
 (1488, 'Mikhaylovsk'),
 (1504, 'Kirov'),
 (1509, 'Moscow'),
 (1538, 'Minsk'),
 (1567, 'Novorossiysk'),
 (1585, 'Kurgan'),
 (1589, 'Magnitogorsk'),
 (1606, 'Prokopyevsk'),
 (1614, 'Lyudinovo'),
 (1616, 'Taganrog'),
 (1640, 'Podolsk'),
 (1642, 'Saint Petersburg'),
 (1656, 'Angarsk'),
 (1658, 'Lermontov'),
 (1664, 'Nikel'),
 (1680, 'Moscow'),
 (1681, 'Sochi'),
 (1686, 'Nizhniy Novgorod'),
 (1691, 'Irkutsk'),
 (1704, 'Moscow'),
 (1712, 'Lviv'),
 (1714, 'Almaty'),
 (1726, 'Karabulak'),
 (1744, 'Mesyagutovo'),
 (1746, 'Kovrov'),
 (1762, 'Saranpaul'),
 (1764, 'Rossosh'),
 (1766, 'Yekaterinburg'),
 (1770, 'Moscow'),
 (1784, 'Saint Petersburg'),
 (1801, 'Arkhangelsk'),
 (1821, 'Saint Petersburg'),
 (1823, 'Minsk'),
 (1836, 'Krasnodar'),
 (1838, 'Obninsk'),
 (1852, 'Almaty'),
 (1856, 'Perm'),
 (1865, 'Moscow'),
 (1886, 'Moscow'),
 (1893, 'Bataysk'),
 (1895, 'Mezhdurechensk'),
 (1901, 'Cherepovets'),
 (1913, 'Novocheboksarsk'),
 (1922, 'Almetyevsk'),
 (1924, 'Volgograd'),
 (1930, 'Staryy Kurdym'),
 (1946, 'Yegoryevsk'),
 (1959, 'Trëkhgornyy'),
 (1961, 'Belgorod'),
 (1964, 'Moscow'),
 (1972, 'Saint Petersburg'),
 (2016, 'Ufa'),
 (2024, 'Moscow'),
 (2033, 'Chusovoy'),
 (2034, 'Novoshakhtinsk'),
 (2035, 'Zarechnyy'),
 (2042, 'Mikhaylovsk'),
 (2045, 'Blagoveshchensk'),
 (2053, 'Kamyshin'),
 (2054, 'İzmir'),
 (2065, 'Saratov'),
 (2082, 'Chegdomyn'),
 (2095, 'Kazan'),
 (2116, 'Kashin'),
 (2139, 'Naberezhnyye Chelny'),
 (2145, 'Saint Petersburg'),
 (2150, 'Anapa'),
 (2152, 'Moscow'),
 (2156, 'Parma'),
 (2171, 'Tyumen'),
 (2193, 'Saint Petersburg'),
 (2197, 'Novosibirsk'),
 (2199, 'Krasnoyarsk'),
 (2204, 'Bor'),
 (2209, 'Qaraçuxur'),
 (2217, 'Moscow'),
 (2218, 'Saransk'),
 (2235, 'Nalchik'),
 (2242, 'Proletarsk'),
 (2249, 'Moscow'),
 (2261, 'Volzhskiy'),
 (2279, 'Moscow'),
 (2291, 'Noginsk'),
 (2292, 'Tyumen'),
 (2293, 'Kyzyl'),
 (2300, 'Obyachevo'),
 (2305, 'Temryuk'),
 (2320, 'Selikhino'),
 (2325, 'Moscow'),
 (2338, 'Kirovo-Chepetsk'),
 (2340, 'Staryy Oskol'),
 (2342, 'Moscow'),
 (2347, 'Yugorsk'),
 (2359, 'Moscow'),
 (2360, 'Kemerovo'),
 (2365, 'Kudymkar'),
 (2375, 'Moscow'),
 (2397, 'Semey'),
 (2410, 'Orekhovo-Zuyevo'),
 (2423, 'Naberezhnyye Chelny'),
 (2452, 'Moscow'),
 (2467, 'Yaroslavl'),
 (2474, 'Nizhniy Novgorod'),
 (2482, 'Kamensk-Shakhtinskiy'),
 (2484, 'Tyumen'),
 (2491, 'Yekaterinburg'),
 (2507, 'Dyshne-Vedeno'),
 (2508, 'Kazan'),
 (2530, 'Tver'),
 (2533, 'Naxçıvan'),
 (2537, 'Novokuznetsk'),
 (2540, 'Chelyabinsk'),
 (2548, 'Poltava'),
 (2602, 'Krymsk'),
 (2621, 'Vidnoye'),
 (2632, 'Kosyno'),
 (2645, 'Izobil’nyy'),
 (2660, 'Moscow'),
 (2666, 'Shchëkino'),
 (2677, 'Yaroslavl'),
 (2679, 'Sion'),
 (2692, 'Almaty'),
 (2705, 'Kazan'),
 (2712, 'Bezopasnoye'),
 (2715, 'Moscow'),
 (2733, 'Angarsk'),
 (2756, 'Kemerovo'),
 (2766, 'Ufa'),
 (2772, 'Valuyki'),
 (2786, 'Voronezh'),
 (2796, 'Moscow'),
 (2821, 'Voronezh'),
 (2822, 'Novocheboksarsk'),
 (2859, 'Khorol'),
 (2877, 'Kaluga'),
 (2883, 'Bataysk'),
 (2892, 'Moscow'),
 (2910, 'Donskoy'),
 (2936, 'Derbent'),
 (2965, 'Andrushky'),
 (2973, 'Krasnoyarsk'),
 (2983, 'Krasnoyarsk'),
 (2994, 'Kazan'),
 (2996, 'Barnaul'),
 (2997, 'Kaluga'),
 (3004, 'Moscow'),
 (3009, 'Saint Petersburg'),
 (3013, 'Moscow'),
 (3019, 'Volgograd'),
 (3044, 'Moscow'),
 (3093, 'Hyvinkää'),
 (3100, 'Kaltan'),
 (3126, 'Cherepovets'),
 (3135, 'Kirov'),
 (3148, 'Bogorodsk'),
 (3158, 'Korolëv'),
 (3170, 'Saint Petersburg'),
 (3173, 'Omsk'),
 (3177, 'Mesyagutovo'),
 (3179, 'Kirsanov'),
 (3187, 'Perm'),
 (3193, 'Moscow'),
 (3204, 'Volgograd'),
 (3251, 'Moscow'),
 (3276, 'Moscow'),
 (3284, 'Nova Kakhovka'),
 (3308, 'Oktyabrskiy'),
 (3316, 'Krasnodar'),
 (3318, 'Moscow'),
 (3346, 'Moscow'),
 (3366, 'Nizhniy Novgorod'),
 (3367, 'Nizhniy Kurkuzhin'),
 (3378, 'Valday'),
 (3386, 'Moscow'),
 (3397, 'Vitsyebsk'),
 (3399, 'Moscow'),
 (3405, 'Podolsk'),
 (3408, 'Nizhniy Tagil'),
 (3409, 'Novosibirsk'),
 (3415, 'Smolensk'),
 (3420, 'Voronezh'),
 (3421, 'Vladivostok'),
 (3424, 'Perm'),
 (3431, 'Sochi'),
 (3467, 'Beloozërskiy'),
 (3473, 'Chelyabinsk'),
 (3475, 'Barnaul'),
 (3476, 'Makhachkala'),
 (3500, 'Maykop'),
 (3503, 'Nizhniy Novgorod'),
 (3529, 'Lyuban’'),
 (3533, 'Magnitogorsk'),
 (3545, 'Moscow'),
 (3554, 'Novomoskovsk'),
 (3560, 'Barnaul'),
 (3570, 'Noginsk'),
 (3582, 'Perm'),
 (3598, 'Saratov'),
 (3629, 'Leninogorsk'),
 (3636, 'Vladimir'),
 (3639, 'Severodvinsk'),
 (3649, 'Tyumen'),
 (3664, 'Espoo'),
 (3668, 'Voskresensk'),
 (3671, 'Lyudinovo'),
 (3679, 'Pervomaisk'),
 (3694, 'Penza'),
 (3699, 'Shalushka'),
 (3725, 'Tomsk'),
 (3733, 'Aqtöbe'),
 (3736, 'Bryansk'),
 (3738, 'Smolensk'),
 (3742, 'Gvazda'),
 (3746, 'Moscow'),
 (3750, 'Ufa'),
 (3759, 'Serdobsk'),
 (3765, 'Yoshkar-Ola'),
 (3766, 'Shiyeli'),
 (3771, 'Cherkasy'),
 (3792, 'Pastavy'),
 (3799, 'Dzyarzhynsk'),
 (3801, 'Chelyabinsk'),
 (3806, 'Neftekamsk'),
 (3807, 'Kazan'),
 (3811, 'Saint Petersburg'),
 (3813, 'Sloviansk'),
 (3819, 'Ivanteyevka'),
 (3825, 'Syktyvkar'),
 (3829, 'Moscow'),
 (3835, 'Zhizdra'),
 (3859, 'Almetyevsk'),
 (3861, 'Novokuznetsk'),
 (3864, 'Irkutsk'),
 (3877, 'Khasavyurt'),
 (3896, 'Tolyatti'),
 (3899, 'Ufa'),
 (3903, 'Mar’’ina Horka'),
 (3905, 'Barnaul'),
 (3913, 'Ivanovka'),
 (3927, 'Murmansk'),
 (3933, 'Tikhvin'),
 (3944, 'Dankov'),
 (3948, 'Moscow'),
 (3953, 'Moscow'),
 (3964, 'Moscow'),
 (3974, 'Vladikavkaz'),
 (3975, 'Benoy'),
 (3985, 'Svetlyy'),
 (4009, 'Bernex'),
 (4013, 'Uzlovaya'),
 (4021, 'Kemerovo'),
 (4027, 'Altud'),
 (4043, 'Ufa'),
 (4053, 'Donetsk'),
 (4067, 'Saint Petersburg'),
 (4069, 'Zabolotiv'),
 (4071, 'Taraz'),
 (4079, 'Kursk'),
 (4100, 'Tomsk'),
 (4107, 'Yegoryevsk'),
 (4123, 'Saint Petersburg'),
 (4134, 'Lice'),
 (4140, 'Yakutsk'),
 (4146, 'Moscow'),
 (4148, 'Palatka'),
 (4151, 'Buy'),
 (4164, 'Novokuybyshevsk'),
 (4177, 'Orenburg'),
 (4194, 'Argun'),
 (4205, 'Buzuluk'),
 (4208, 'Bavly'),
 (4237, 'Tara'),
 (4253, 'Kamyshin'),
 (4262, 'Neryungri'),
 (4265, 'Zlatoust'),
 (4268, 'Moscow'),
 (4294, 'Moscow'),
 (4296, 'Moscow'),
 (4299, 'Yany Kapu'),
 (4309, 'Ulyanovsk'),
 (4313, 'Saratov'),
 (4314, 'Engels'),
 (4320, 'Antalya'),
 (4358, 'Apatity'),
 (4360, 'Saint Petersburg'),
 (4362, 'Petrozavodsk'),
 (4365, 'Homyel’'),
 (4369, 'Novokuznetsk'),
 (4377, 'Kamyshin'),
 (4383, 'Barnaul'),
 (4398, 'Russkoye'),
 (4402, 'Moscow'),
 (4405, 'Iglino'),
 (4406, 'Ufa'),
 (4418, 'Makiivka'),
 (4424, 'Saint Petersburg'),
 (4426, 'Saint Petersburg'),
 (4430, 'Moscow'),
 (4432, 'Helsinki'),
 (4437, 'Krasnoyarsk'),
 (4464, 'Samara'),
 (4469, 'Rossosh'),
 (4475, 'Saint Petersburg'),
 (4488, 'Kamennogorsk'),
 (4492, 'Moscow'),
 (4493, 'Dnipro'),
 (4498, 'Kyiv'),
 (4511, 'Engels'),
 (4515, 'Ust’-Ilimsk'),
 (4517, 'Ak-Dovurak'),
 (4529, 'Malyn'),
 (4531, 'Irkutsk'),
 (4538, 'Kazan'),
 (4546, 'Novosibirsk'),
 (4553, 'Shyshaky'),
 (4557, 'Pereslavl’-Zalesskiy'),
 (4562, 'Novosibirsk'),
 (4567, 'Perm'),
 (4573, 'Odesa'),
 (4598, 'Kryvyi Rih'),
 (4600, 'Arkhangelsk'),
 (4625, 'Angarsk'),
 (4626, 'Moscow'),
 (4627, 'Novozybkov'),
 (4631, 'Saint Petersburg'),
 (6155, 'Kotlas'),
 (4652, 'Slantsy'),
 (4654, 'Stavropol'),
 (4662, 'Yaroslavl'),
 (4670, 'Kopeysk'),
 (4673, 'Mariinsk'),
 (4681, 'Yekaterinburg'),
 (4687, 'Saint Petersburg'),
 (4691, 'Tver'),
 (4699, 'Novosibirsk'),
 (4707, 'Staryy Oskol'),
 (4713, 'Saarijärvi'),
 (4714, 'Chernivtsi'),
 (4715, 'Yelets'),
 (4727, 'Khimki'),
 (4734, 'Kochki'),
 (4749, 'Staryye Atagi'),
 (4750, 'Nur-Sultan'),
 (4757, 'Perm'),
 (4779, 'Şirvan'),
 (4782, 'Moscow'),
 (4808, 'Alleroy'),
 (4824, 'Tiachiv'),
 (4861, 'Krasnoyarsk'),
 (4896, 'Novosibirsk'),
 (4897, 'Krasnoyarsk'),
 (4906, 'Bryansk'),
 (4907, 'Murmansk'),
 (4922, 'Novovoronezh'),
 (4929, 'Samara'),
 (4933, 'Verkhniy Tagil'),
 (4936, 'Pskov'),
 (4957, 'Gavrilov-Yam'),
 (4960, 'Ozërsk'),
 (4969, 'Vladivostok'),
 (4994, 'Saint Petersburg'),
 (4999, 'Yelets'),
 (5004, 'Bryansk'),
 (5007, 'Ulyanovsk'),
 (5025, 'Moscow'),
 (5029, 'Krasnoufimsk'),
 (5040, 'Ryazan'),
 (5043, 'Saint Petersburg'),
 (5050, 'Kamensk-Shakhtinskiy'),
 (5056, 'Saint Petersburg'),
 (5057, 'Maykop'),
 (7136, 'Moscow'),
 (5074, 'Magnitogorsk'),
 (5080, 'Rivne'),
 (5091, 'Vladivostok'),
 (5103, 'Vologda'),
 (5142, 'Volgograd'),
 (5148, 'Kharkiv'),
 (5157, 'Saint Petersburg'),
 (5172, 'Tomsk'),
 (5173, 'Moscow'),
 (5179, 'Ust’-Ilimsk'),
 (5189, 'Moscow'),
 (5205, 'Slavyansk-na-Kubani'),
 (5213, 'Astrakhan'),
 (5223, 'Yekaterinburg'),
 (5236, 'Smolensk'),
 (5243, 'Moscow'),
 (5256, 'Rostov'),
 (5261, 'Shymkent'),
 (5270, 'Kolchugino'),
 (5275, 'Zheleznogorsk'),
 (5293, 'Tambov'),
 (5297, 'Moscow'),
 (5302, 'Helsinki'),
 (5305, 'Velykyi Bychkiv'),
 (5307, 'Chemal'),
 (5330, 'Moscow'),
 (5339, 'Moscow'),
 (5341, 'Moscow'),
 (5342, 'Moscow'),
 (5352, 'Kherson'),
 (5368, 'Moscow'),
 (5380, 'Nizhniy Novgorod'),
 (5409, 'Yershov'),
 (5416, 'Kemerovo'),
 (5422, 'Novosibirsk'),
 (5431, 'Krasnokamsk'),
 (5435, 'Saratov'),
 (5437, 'Kremenchuk'),
 (5444, 'Nizhnevartovsk'),
 (5452, 'Khimki'),
 (5459, 'Kotlas'),
 (5464, 'Samara'),
 (5465, 'Saint Petersburg'),
 (5466, 'Moscow'),
 (5523, 'Mariupol'),
 (5525, 'Podolsk'),
 (5541, 'Gulkevichi'),
 (5555, 'Volgograd'),
 (5562, 'Ulan-Ude'),
 (5580, 'Kandry'),
 (5593, 'Kazan'),
 (5600, 'Nizhniy Novgorod'),
 (5609, 'Vyksa'),
 (5623, 'Bavly'),
 (5628, 'Kondopoga'),
 (5643, 'Syktyvkar'),
 (5652, 'Moscow'),
 (5661, 'Georgiyevsk'),
 (5666, 'Minsk'),
 (5667, 'Nizhniy Novgorod'),
 (5684, 'Kazan'),
 (5694, 'Moscow'),
 (5704, 'Blagodarnyy'),
 (5708, 'Almaty'),
 (5711, 'Ivanovo'),
 (5750, 'Volzhskiy'),
 (5751, 'Trëkhgornyy'),
 (5755, 'Tosno'),
 (5764, 'Krasnodar'),
 (5769, 'Nevyansk'),
 (5784, 'Buynaksk'),
 (5798, 'Gatchina'),
 (5801, 'Kamenka'),
 (5813, 'Nizhneudinsk'),
 (5822, 'Qaraghandy'),
 (5832, 'Saint Petersburg'),
 (5850, 'Saint Petersburg'),
 (5856, 'Saint Petersburg'),
 (5859, 'Omsk'),
 (5866, 'Krasnoyarsk'),
 (5875, 'Moscow'),
 (5877, 'Moscow'),
 (5883, 'Saint Petersburg'),
 (5899, 'Kamensk-Ural’skiy'),
 (5905, 'Saratov'),
 (5908, 'Tinit'),
 (5911, 'Taganrog'),
 (5916, 'Saint Petersburg'),
 (5919, 'Korosten'),
 (5924, 'Moscow'),
 (5930, 'Vladikavkaz'),
 (5949, 'Shakhty'),
 (5950, 'Troitsk'),
 (5953, 'Saint Petersburg'),
 (5971, 'Odesa'),
 (5974, 'Dnipro'),
 (5976, 'Kropotkin'),
 (5977, 'Kazan'),
 (5981, 'Barnaul'),
 (5983, 'Novocherkassk'),
 (6003, 'Fryazino'),
 (6004, 'Chernogorsk'),
 (6013, 'Nizhniy Novgorod'),
 (6014, 'Berezniki'),
 (6038, 'Rubtsovsk'),
 (6042, 'Kochubeyevskoye'),
 (6057, 'Konakovo'),
 (6065, 'Moscow'),
 (6082, 'Saint Petersburg'),
 (6104, 'Kukmor'),
 (6109, 'Tolyatti'),
 (6114, 'Yaroslavl'),
 (6117, 'Yekaterinburg'),
 (6121, 'Ufa'),
 (6124, 'Volgograd'),
 (6167, 'Moscow'),
 (6176, 'Qarataū'),
 (6180, 'Moscow'),
 (6182, 'Mytishchi'),
 (6186, 'Yakutsk'),
 (6187, 'Moscow'),
 (6196, 'Yalutorovsk'),
 (6205, 'Insar'),
 (6211, 'Luhansk'),
 (6213, 'Uryupinsk'),
 (6216, 'Moscow'),
 (6221, 'Saint Petersburg'),
 (6227, 'Ivdel'),
 (6234, 'Severodvinsk'),
 (6238, 'Murom'),
 (6263, 'Orenburg'),
 (6265, 'Moscow'),
 (6277, 'Ankara'),
 (6288, 'Esik'),
 (6311, 'Kommunar'),
 (6322, 'Saint Petersburg'),
 (6333, 'Kyiv'),
 (6334, 'Novokuznetsk'),
 (6337, 'Chelyabinsk'),
 (6342, 'Moscow'),
 (6362, 'Moscow'),
 (6376, 'Apsheronsk'),
 (6382, 'Moscow'),
 (6413, 'Mtsensk'),
 (6431, 'Şəki'),
 (6434, 'Donetsk'),
 (6442, 'Krasnyy Kholm'),
 (6446, 'Moscow'),
 (6451, 'Leninsk'),
 (6459, 'Liski'),
 (6460, 'Berezniki'),
 (6472, 'Saint Petersburg'),
 (6476, 'Yuzhno-Sukhokumsk'),
 (6479, 'Velikiye Luki'),
 (6485, 'Petropavl'),
 (6498, 'Moscow'),
 (6518, 'Tolyatti'),
 (6530, 'Klin'),
 (6566, 'Kirov'),
 (6568, 'Antalya'),
 (6570, 'Khimki'),
 (6575, 'Chita'),
 (6582, 'Moscow'),
 (6601, 'Azov'),
 (6604, 'Tomsk'),
 (6612, 'Voronezh'),
 (6627, 'Saint Petersburg'),
 (6633, 'Severodvinsk'),
 (6647, 'Belgorod'),
 (6655, 'Yuzha'),
 (6658, 'Ozërsk'),
 (6660, 'Kobeliaky'),
 (6661, 'Rostov'),
 (6691, 'Voronezh'),
 (6695, 'Volzhskiy'),
 (6699, 'Ekazhevo'),
 (6710, 'Belëv'),
 (6713, 'Moscow'),
 (6714, 'Saint Petersburg'),
 (6722, 'Voronezh'),
 (6723, 'Cheboksary'),
 (6737, 'Omsk'),
 (6739, 'Yartsevo'),
 (6742, 'Shelekhov'),
 (6757, 'Moscow'),
 (6771, 'Yelets'),
 (6785, 'Krasnoyarsk'),
 (6819, 'Dimitrovgrad'),
 (6824, 'Ob'),
 (6832, 'Moscow'),
 (6833, 'Kharkiv'),
 (6842, 'Chita'),
 (6843, 'Balakovo'),
 (6854, 'Dnipro'),
 (6857, 'Moscow'),
 (6859, 'Saint Petersburg'),
 (6861, 'Moscow'),
 (6862, 'Azov'),
 (6871, 'Ufa'),
 (6874, 'Culfa'),
 (6879, 'Soldato-Aleksandrovskoye'),
 (6891, 'Kokhma'),
 (6900, 'Yessentuki'),
 (6902, 'Kaliningrad'),
 (6914, 'Kavalerovo'),
 (6952, 'Minsk'),
 (6956, 'Yekaterinburg'),
 (6960, 'Tikhvin'),
 (6965, 'Orekhovo-Borisovo Yuzhnoye'),
 (6970, 'Moscow'),
 (6981, 'Kazan'),
 (7000, 'Tsiolkovskiy'),
 (7009, 'Krasnodar'),
 (7011, 'Chita'),
 (7012, 'Uvarovo'),
 (7013, 'Moscow'),
 (7025, 'Lipetsk'),
 (7036, 'Zheleznogorsk'),
 (7045, 'Perm'),
 (7051, 'Morshansk'),
 (7063, 'Bratsk'),
 (7069, 'Nizhniy Novgorod'),
 (7083, 'Irkutsk'),
 (7098, 'Rezh'),
 (7100, 'Moscow'),
 (7106, 'Krasnokumskoye'),
 (7111, 'Chernihiv'),
 (7115, 'Aginskoye'),
 (7147, 'Zhigulevsk'),
 (7160, 'Aleysk'),
 (7190, 'Yekaterinburg'),
 (7198, 'Pavlohrad'),
 (7205, 'Noginsk'),
 (7220, 'Moscow'),
 (7225, 'Minsk'),
 (7226, 'Chita'),
 (7230, 'Mykolaiv'),
 (7236, 'Kamenka'),
 (7238, 'Makhachkala'),
 (7247, 'Derbent'),
 (7273, 'Mingəçevir'),
 (7275, 'Saint Petersburg'),
 (7281, 'Tyumen'),
 (7294, 'Balakovo'),
 (7297, 'Sarapul'),
 (7299, 'Sudak'),
 (7314, 'Kusa'),
 (7320, 'Bratsk'),
 (7321, 'Sarov'),
 (7336, 'Michurinsk'),
 (7338, 'Cheboksary'),
 (7339, 'Saint Petersburg'),
 (7344, 'Atbasar'),
 (7355, 'Gaziantep'),
 (7357, 'Ufa'),
 (7361, 'Sarapul'),
 (7365, 'Moscow'),
 (7366, 'Safonovo'),
 (7397, 'Ishimbay'),
 (7407, 'Drohobych'),
 (7412, 'Kolpino'),
 (7413, 'Yaroslavl'),
 (7419, 'Moscow'),
 (7453, 'Tolyatti'),
 (7464, 'Nizhniy Novgorod'),
 (7472, 'Lobnya'),
 (7478, 'Volgograd'),
 (7499, 'Saint Petersburg'),
 (7503, 'Nizhnevartovsk'),
 (7510, 'Vladimir'),
 (7512, 'Adana'),
 (7516, 'Slyudyanka'),
 (7525, 'Berezniki'),
 (7556, 'Kasli'),
 (7560, 'Michurinsk'),
 (7584, 'Kazan'),
 (7597, 'Kyiv'),
 (7600, 'Novosibirsk'),
 (7611, 'Bolkhov'),
 (7613, 'Zaporizhzhia'),
 (7614, 'Tula'),
 (7618, 'Saratov'),
 (7635, 'Moscow'),
 (7642, 'Orsk'),
 (7644, 'Podolsk'),
 (7646, 'Saint Petersburg'),
 (7656, 'Saratov'),
 (7657, 'Saint Petersburg'),
 (7704, 'Barnaul'),
 (7719, 'Arkhangelsk'),
 (7723, 'Moscow'),
 (7733, 'Moscow'),
 (7746, 'Apatity'),
 (7752, 'Moscow'),
 (7791, 'Astrakhan'),
 (7797, 'Omsk'),
 (7816, 'Moscow'),
 (7831, 'Ufa'),
 (7836, 'Cherepovets'),
 (7865, 'Moscow'),
 (7883, 'Moscow'),
 (7886, 'Ulyanovsk'),
 (7888, 'Kaluga'),
 (7901, 'Nurlino'),
 (7917, 'Volgograd'),
 (7918, 'Khadyzhensk'),
 (7925, 'Moscow'),
 (7927, 'Moscow'),
 (7951, 'Yazykovo'),
 (7953, 'Ufa'),
 (7965, 'Balakovo'),
 (7994, 'Samara'),
 (8003, 'Tver'),
 (8012, 'Kyiv'),
 (8013, 'Nerekhta'),
 (8023, 'Saint Petersburg'),
 (8028, 'Balashikha'),
 (8043, 'Astrakhan'),
 (8053, 'Moscow'),
 (8059, 'Krasnotur’insk'),
 (8061, 'Azov'),
 (8065, 'Bryansk'),
 (8069, 'Moscow'),
 (8078, 'Astrakhan'),
 (8086, 'Omsk'),
 (8096, 'Vadinsk'),
 (8099, 'Tubinskiy'),
 (8112, 'Moscow'),
 (8114, 'Moscow'),
 (8121, 'Kratovo'),
 (8127, 'Maydakovo'),
 (8138, 'Tatarsk'),
 (8163, 'Petropavlovsk-Kamchatskiy'),
 (8202, 'Rostov'),
 (8203, 'Orenburg'),
 (8207, 'Ishim'),
 (8212, 'Lyubertsy'),
 (8213, 'Minsk'),
 (8214, 'Haisyn'),
 (8218, 'Glazov'),
 (8226, 'Ust’-Kut'),
 (8256, 'Tambov'),
 (8262, 'Mangghystaū'),
 (8267, 'Saint Petersburg'),
 (8270, 'Meleuz'),
 (8271, 'Saint Petersburg'),
 (8287, 'Novovyatsk'),
 (8290, 'Moscow'),
 (8291, 'Odesa'),
 (8317, 'Syasstroy'),
 (8318, 'Gavrilov-Yam'),
 (8326, 'Saint Petersburg'),
 (8337, 'Yemva'),
 (8342, 'Karmaskaly'),
 (8347, 'Giresun'),
 (8359, 'Sibay'),
 (8360, 'Vladikavkaz'),
 (8368, 'Perm'),
 (8385, 'Saint Petersburg'),
 (8390, 'Kurchatov'),
 (8398, 'Lutsk'),
 (8409, 'Kirov'),
 (8410, 'Novyy Urengoy'),
 (8437, 'Diyarbakır'),
 (8471, 'Vologda'),
 (8479, 'Anapa'),
 (8484, 'Saratov'),
 (8508, 'Moscow'),
 (8509, 'Moscow'),
 (8524, 'Moscow'),
 (8534, 'Zheleznogorsk'),
 (8538, 'Penza'),
 (8547, 'Krasnoyarsk'),
 (8555, 'Kislovodsk'),
 (8562, 'Moscow'),
 (8565, 'Krasnodar'),
 (8568, 'Omsk'),
 (8572, 'Perm'),
 (8592, 'Minsk'),
 (8595, 'Amvrosiivka'),
 (8600, 'Moscow'),
 (8602, 'Ryazan'),
 (8625, 'Tyumen'),
 (8630, 'Krasnoufimsk'),
 (8640, 'Moscow'),
 (8641, 'Saint Petersburg'),
 (8650, 'Engels'),
 (8652, 'Moscow'),
 (8654, 'Mala Uhol’ka'),
 (8656, 'Poltava'),
 (8660, 'Murmansk'),
 (8662, 'Yuzhnouralsk'),
 (8692, 'Gatchina'),
 (8709, 'Vidnoye'),
 (8725, 'Kaliningrad'),
 (8741, 'Moscow'),
 (8752, 'Krasnoyarsk'),
 (8766, 'Lida'),
 (8771, 'Saratov'),
 (8774, 'Novosibirsk'),
 (8781, 'Seversk'),
 (8793, 'Moscow'),
 (8798, 'Chita'),
 (8799, 'Almaty'),
 (8800, 'Krasnodar'),
 (8804, 'Chelyabinsk'),
 (8828, 'Sochi'),
 (8831, 'Yessentuki'),
 (8832, 'Pytalovo'),
 (8843, 'Shali'),
 (8846, 'Nizhniy Tagil'),
 (8847, 'Moscow'),
 (8883, 'Sovetsk'),
 (8890, 'Staryy Oskol'),
 (8897, 'Gəncə'),
 (8900, 'Moscow'),
 (8907, 'Chusovoy'),
 (8911, 'Lyubertsy'),
 (8919, 'Balashikha'),
 (8922, 'Moscow'),
 (8929, 'Balashov'),
 (8934, 'Surgut'),
 (8940, 'Tara'),
 (8943, 'Krasnoyarsk'),
 (8945, 'Moscow'),
 (8950, 'Gus’-Khrustal’nyy'),
 (8963, 'Kazan'),
 (8966, 'Kodinsk'),
 (8970, 'Makhachkala'),
 (8973, 'Salavat'),

In [8]:
cursor.execute('''
SELECT id, exp_group, city FROM "user"
WHERE NOT country = 'Russia' AND NOT exp_group = 0 AND NOT exp_group = 3 OR city = 'Minsk'
''')

results = cursor.fetchall()
results

# cursor.close()
# connection.close()

[(211, 0, 'Minsk'),
 (213, 2, 'Kamianske'),
 (216, 1, 'Lviv'),
 (218, 2, 'Minsk'),
 (228, 2, 'Baku'),
 (243, 1, 'Ekibastuz'),
 (271, 2, 'Gaziantep'),
 (273, 2, 'Ağcabədi'),
 (276, 1, 'Asipovichy'),
 (329, 4, 'Novohrad-Volynskyi'),
 (351, 2, 'Sevastopol'),
 (421, 2, 'Siyəzən'),
 (442, 2, 'Romny'),
 (443, 1, 'Truskavets'),
 (448, 2, 'Alchevsk'),
 (454, 1, 'Druzhkivka'),
 (461, 1, 'Minsk'),
 (480, 4, 'Velykyi Bychkiv'),
 (481, 4, 'Ağdaş'),
 (495, 1, 'Novosamarka'),
 (507, 1, 'Virolahti'),
 (528, 1, 'Irpin'),
 (545, 1, 'Taraz'),
 (556, 4, 'Antalya'),
 (567, 4, 'Minsk'),
 (571, 2, 'Helsinki'),
 (592, 4, 'Cēsis'),
 (603, 1, 'Erzincan'),
 (622, 2, 'Konya'),
 (646, 4, 'Əmircan'),
 (657, 2, 'Makiivka'),
 (664, 3, 'Minsk'),
 (677, 1, 'Enerhodar'),
 (692, 1, 'Mersin'),
 (702, 2, 'Berdiansk'),
 (709, 4, 'Kobryn'),
 (725, 4, 'Nicosia'),
 (731, 2, 'Tampere'),
 (741, 4, 'Homyel’'),
 (764, 1, 'Baku'),
 (786, 1, 'Velyka Mykhailivka'),
 (788, 1, 'Kyiv'),
 (795, 2, 'Sumy'),
 (830, 1, 'Hlukhiv'),
 (848, 2, 'Riga'),
 (854, 1, 'Ayagöz'),
 (855, 4, 'Homyel’'),
 (903, 2, 'Nur-Sultan'),
 (909, 4, 'Rivne'),
 (925, 1, 'Kharkiv'),
 (933, 4, 'Öskemen'),
 (934, 1, 'Drohobych'),
 (942, 4, 'Nur-Sultan'),
 (954, 4, 'Baku'),
 (959, 2, 'Baku'),
 (1000, 2, 'Kayseri'),
 (1001, 2, 'Istanbul'),
 (1018, 1, 'Smila'),
 (1032, 4, 'Vilyeyka'),
 (1049, 2, 'Poltava'),
 (1081, 1, 'Öskemen'),
 (1085, 1, 'Khmelnytskyi'),
 (1090, 2, 'Homyel’'),
 (1095, 4, 'Nicosia'),
 (1107, 4, 'Homyel’'),
 (1109, 4, 'Minsk'),
 (1115, 1, 'Helsinki'),
 (1124, 4, 'Kharkiv'),
 (1162, 1, 'Konotop'),
 (1173, 4, 'Stakhanov'),
 (1177, 4, 'Hamina'),
 (1195, 2, 'Mykolaiv'),
 (1216, 4, 'Minsk'),
 (1219, 2, 'Kherson'),
 (1223, 2, 'Kherson'),
 (1230, 4, 'Diyarbakır'),
 (1240, 4, 'Voznesensk'),
 (1258, 4, 'Oulu'),
 (1270, 4, 'Dnipro'),
 (1274, 4, 'Kyiv'),
 (1275, 2, 'Izmail'),
 (1276, 4, 'Pinsk'),
 (1292, 1, 'Alchevsk'),
 (1311, 2, 'Brest'),
 (1312, 2, 'Berdiansk'),
 (1317, 4, 'Minsk'),
 (1318, 4, 'Kryvyi Rih'),
 (1366, 1, 'Ternopil'),
 (1375, 0, 'Minsk'),
 (1385, 2, 'Qyzylorda'),
 (1402, 1, 'Oulu'),
 (1433, 4, 'Izmail'),
 (1445, 1, 'Voloske'),
 (1449, 1, 'Kamianske'),
 (1450, 1, 'Aqtaū'),
 (1452, 3, 'Minsk'),
 (1458, 2, 'Homyel’'),
 (1459, 1, 'Mazyr'),
 (1478, 4, 'Kropyvnytskyi'),
 (1490, 2, 'Limassol'),
 (1514, 4, 'Vinnytsia'),
 (1515, 4, 'Varkaus'),
 (1524, 4, 'Petropavl'),
 (1538, 2, 'Minsk'),
 (1543, 4, 'Qyzylorda'),
 (1562, 4, 'Homyel’'),
 (1570, 4, 'Oral'),
 (1590, 4, 'Kouvola'),
 (1591, 4, 'Nur-Sultan'),
 (1594, 1, 'Pavlohrad'),
 (1600, 4, 'Dnipro'),
 (1696, 2, 'Zhytomyr'),
 (1712, 1, 'Lviv'),
 (1713, 2, 'Cherkasy'),
 (1714, 2, 'Almaty'),
 (1718, 1, 'Odesa'),
 (1724, 2, 'Baku'),
 (1725, 4, 'Kovel'),
 (1727, 2, 'Mukacheve'),
 (1737, 0, 'Minsk'),
 (1753, 2, 'Stanytsia Luhanska'),
 (1756, 2, 'Bolhrad'),
 (1781, 2, 'Svitlohirske'),
 (1792, 1, 'Lutsk'),
 (1799, 2, 'Baku'),
 (1809, 1, 'Khrustalnyi'),
 (1823, 2, 'Minsk'),
 (1824, 1, 'Barvynkove'),
 (1844, 4, 'Ternopil'),
 (1852, 4, 'Almaty'),
 (1881, 1, 'Minsk'),
 (1926, 1, 'Baku'),
 (1927, 4, 'Baku'),
 (1963, 1, 'Mykolaiv'),
 (1975, 4, 'Gəncə'),
 (1995, 4, 'Kyiv'),
 (1999, 2, 'Sloviansk'),
 (2010, 0, 'Minsk'),
 (2013, 1, 'Shabelkivka'),
 (2054, 4, 'İzmir'),
 (2063, 2, 'Brest'),
 (2071, 2, 'Qostanay'),
 (2097, 1, 'Mariehamn'),
 (2101, 1, 'Minsk'),
 (2110, 1, 'Selydove'),
 (2122, 1, 'Nikopol'),
 (2128, 4, 'Melitopol'),
 (2130, 2, 'Zaporizhzhia'),
 (2160, 2, 'Pavlohrad'),
 (2175, 1, 'Baranavichy'),
 (2209, 4, 'Qaraçuxur'),
 (2210, 1, 'Mykolaiv'),
 (2214, 1, 'Qostanay'),
 (2245, 2, 'Asipovichy'),
 (2247, 4, 'Minsk'),
 (2252, 2, 'Almaty'),
 (2262, 1, 'Lviv'),
 (2268, 1, 'Lahti'),
 (2278, 2, 'Bandırma'),
 (2280, 4, 'Svyetlahorsk'),
 (2284, 2, 'Vantaa'),
 (2296, 2, 'Horad Barysaw'),
 (2308, 2, 'Vitsyebsk'),
 (2313, 2, 'Dnipro'),
 (2350, 4, 'Mariupol'),
 (2351, 2, 'Samsun'),
 (2354, 1, 'Koviahy'),
 (2358, 1, 'Kyiv'),
 (2379, 2, 'M.Ə. Rəsulzadə'),
 (2382, 2, 'Yany Kapu'),
 (2387, 1, 'Kirkkonummi'),
 (2397, 4, 'Semey'),
 (2424, 4, 'Minsk'),
 (2429, 4, 'Larsmo'),
 (2438, 4, 'Luhansk'),
 (2442, 2, 'Pinsk'),
 (2446, 1, 'Larnaca'),
 (2454, 4, 'Senkevychivka'),
 (2457, 4, 'Cherkasy'),
 (2463, 4, 'Avdiivka'),
 (2495, 1, 'Koziatyn'),
 (2499, 1, 'Polohy'),
 (2503, 1, 'Kharkiv'),
 (2509, 2, 'İnegöl'),
 (2515, 2, 'Minsk'),
 (2516, 2, 'Gəncə'),
 (2525, 2, 'Almaty'),
 (2528, 1, 'Kyiv'),
 (2531, 2, 'Kauniainen'),
 (2533, 2, 'Naxçıvan'),
 (2570, 1, 'Valozhyn'),
 (2590, 1, 'Espoo'),
 (2611, 4, 'Göyçay'),
 (2616, 2, 'Semey'),
 (2622, 2, 'Vantaa'),
 (2629, 4, 'Aral'),
 (2654, 2, 'Dnipro'),
 (2676, 1, 'Melitopol'),
 (2679, 2, 'Sion'),
 (2685, 2, 'Nokia'),
 (2722, 1, 'Almaty'),
 (2729, 3, 'Minsk'),
 (2730, 2, 'Kyiv'),
 (2731, 4, 'Khmelnytskyi'),
 (2818, 2, 'Antalya'),
 (2835, 2, 'Kobryn'),
 (2842, 2, 'Almaty'),
 (2848, 2, 'Kauniainen'),
 (2864, 2, 'Rivne'),
 (2865, 4, 'Imatra'),
 (2869, 4, 'Khmelnytskyi'),
 (2881, 1, 'Pastavy'),
 (2887, 1, 'Staryi Mizun'),
 (2888, 1, 'Kyiv'),
 (2890, 4, 'Baku'),
 (2897, 2, 'Vitsyebsk'),
 (2907, 2, 'Tampere'),
 (2921, 1, 'Istanbul'),
 (2922, 1, 'Shymkent'),
 (2938, 3, 'Minsk'),
 (2944, 4, 'Zhytomyr'),
 (2963, 4, 'Adana'),
 (2965, 4, 'Andrushky'),
 (2992, 4, 'Minsk'),
 (3003, 2, 'Almaty'),
 (3005, 0, 'Minsk'),
 (3007, 4, 'Joroinen'),
 (3042, 4, 'Sumy'),
 (3043, 4, 'Semey'),
 (3055, 4, 'Zhytomyr'),
 (3070, 4, 'Bakhchysarai'),
 (3112, 2, 'Helsinki'),
 (3119, 4, 'Zhetisay'),
 (3120, 1, 'Liperi'),
 (3133, 4, 'Hubynykha'),
 (3137, 4, 'Kyiv'),
 (3149, 4, 'Kamianske'),
 (3167, 4, 'Engure'),
 (3186, 1, 'Korop'),
 (3219, 2, 'Bandırma'),
 (3234, 4, 'Horad Barysaw'),
 (3250, 2, 'Aral'),
 (3263, 1, 'Luninyets'),
 (3284, 4, 'Nova Kakhovka'),
 (3295, 2, 'Minsk'),
 (3324, 2, 'Horlivka'),
 (3327, 1, 'Minsk'),
 (3331, 4, 'Tornio'),
 (3332, 2, 'Donetsk'),
 (3396, 2, 'Shymkent'),
 (3444, 2, 'Kyiv'),
 (3448, 4, 'Kryvyi Rih'),
 (3497, 4, 'Minsk'),
 (3506, 3, 'Minsk'),
 (3518, 4, 'Nahiryanka'),
 (3529, 1, 'Lyuban’'),
 (3535, 2, 'Baku'),
 (3538, 4, 'Almaty'),
 (3573, 2, 'Byalynichy'),
 (3587, 1, 'Lice'),
 (3588, 1, 'Donetsk'),
 (3594, 2, 'Mersin'),
 (3610, 1, 'Bila Tserkva'),
 (3615, 2, 'Horlivka'),
 (3624, 4, 'Andriivka'),
 (3634, 4, 'Kharkiv'),
 (3651, 4, 'Makiivka'),
 (3679, 2, 'Pervomaisk'),
 (3683, 4, 'Kharkiv'),
 (3691, 1, 'Kamianske'),
 (3720, 4, 'Melitopol'),
 (3749, 1, 'Zaslawye'),
 (3763, 1, 'Staryy Beyneu'),
 (3772, 1, 'Shū'),
 (3780, 1, 'Pinsk'),
 (3792, 1, 'Pastavy'),
 (3832, 1, 'Lviv'),
 (3837, 1, 'Pomarkku'),
 (3863, 1, 'Mersin'),
 (3875, 2, 'Berdiansk'),
 (3883, 0, 'Minsk'),
 (3889, 1, 'Mahilyow'),
 (3903, 1, 'Mar’’ina Horka'),
 (3919, 4, 'Zelenodolsk'),
 (3929, 2, 'Dnipro'),
 (3936, 2, 'Kharkiv'),
 (3946, 4, 'Krupki'),
 (3955, 1, 'Kherson'),
 (3958, 1, 'Baku'),
 (3993, 2, 'Qaraghandy'),
 (4009, 2, 'Bernex'),
 (4049, 4, 'Maladzyechna'),
 (4053, 4, 'Donetsk'),
 (4064, 4, 'Khartsyzk'),
 (4071, 2, 'Taraz'),
 (4080, 2, 'Krasnoilsk'),
 (4086, 1, 'Minsk'),
 (4099, 2, 'Almaty'),
 (4125, 1, 'Horlivka'),
 (4136, 2, 'Zürich'),
 (4144, 2, 'Dnipro'),
 (4145, 1, 'Fribourg'),
 (4152, 2, 'Vantaa'),
 (4165, 2, 'Donetsk'),
 (4170, 4, 'Zaporizhzhia'),
 (4190, 4, 'Maştağa'),
 (4193, 4, 'Aqtöbe'),
 (4196, 1, 'Minsk'),
 (4217, 4, 'Tallinn'),
 (4225, 1, 'Tampere'),
 (4240, 4, 'Horad Barysaw'),
 (4251, 4, 'Berehove'),
 (4252, 2, 'Daugavpils'),
 (4263, 4, 'Viljandi'),
 (4288, 4, 'Qaraghandy'),
 (4299, 1, 'Yany Kapu'),
 (4317, 4, 'Istanbul'),
 (4320, 1, 'Antalya'),
 (4322, 1, 'Kyiv'),
 (4334, 1, 'Vaasa'),
 (4345, 2, 'Odesa'),
 (4368, 1, 'Lahti'),
 (4375, 4, 'Dnipro'),
 (4396, 1, 'Berestechko'),
 (4450, 2, 'Donetsk'),
 (4453, 4, 'Dzhankoi'),
 (4460, 4, 'Qulsary'),
 (4461, 4, 'Nur-Sultan'),
 (4467, 4, 'Donetsk'),
 (4482, 4, 'Zhetisay'),
 (4493, 4, 'Dnipro'),
 (4498, 1, 'Kyiv'),
 (4503, 4, 'Mänttä'),
 (4505, 2, 'Vantaa'),
 (4528, 2, 'Nur-Sultan'),
 (4529, 4, 'Malyn'),
 (4551, 1, 'Minsk'),
 (4560, 4, 'Kobryn'),
 (4569, 2, 'Huiva'),
 (4573, 4, 'Odesa'),
 (4599, 2, 'Zvejniekciems'),
 (4615, 4, 'Slavutych'),
 (4619, 4, 'Brest'),
 (4628, 2, 'Istanbul'),
 (4629, 1, 'Kamianets-Podilskyi'),
 (4635, 1, 'Adana'),
 (4640, 2, 'Hrodna'),
 (4679, 4, 'Tyrnävä'),
 (4685, 4, 'Vantaa'),
 (4686, 2, 'Nur-Sultan'),
 (4688, 1, 'Zolotonosha'),
 (4713, 4, 'Saarijärvi'),
 (4722, 2, 'Qaraghandy'),
 (4730, 4, 'Atyraū'),
 (4742, 1, 'Lutsk'),
 (4745, 1, 'Qaraghandy'),
 (4746, 1, 'Orsha'),
 (4750, 2, 'Nur-Sultan'),
 (4762, 1, 'Petropavl'),
 (4768, 2, 'Nemyriv'),
 (4779, 4, 'Şirvan'),
 (4799, 2, 'İzmir'),
 (4800, 4, 'Gəncə'),
 (4806, 4, 'Rivne'),
 (4824, 4, 'Tiachiv'),
 (4825, 1, 'Yevpatoriia'),
 (4833, 2, 'Chernihiv'),
 (4840, 1, 'İzmir'),
 (4856, 4, 'Helsinki'),
 (4857, 1, 'Odesa'),
 (4864, 4, 'Elgg'),
 (4881, 1, 'Sumqayıt'),
 (4900, 1, 'Petropavl'),
 (4937, 4, 'Kamianske'),
 (5030, 4, 'Hrodna'),
 (5032, 4, 'Mahilyow'),
 (5036, 1, 'Hrodna'),
 (5055, 4, 'Kyiv'),
 (5059, 2, 'Baku'),
 (5072, 4, 'Oral'),
 (5081, 4, 'Géri'),
 (5086, 2, 'Tampere'),
 (5131, 1, 'Kyiv'),
 (5182, 2, 'Nur-Sultan'),
 (5195, 1, 'Radomyshl'),
 (5199, 1, 'Sumqayıt'),
 (5211, 1, 'Öskemen'),
 (5250, 2, 'Liepāja'),
 (5261, 4, 'Shymkent'),
 (5265, 4, 'Minsk'),
 (5291, 4, 'Ivano-Frankivsk'),
 (5295, 1, 'Almaty'),
 (5305, 4, 'Velykyi Bychkiv'),
 (5312, 4, 'Vitsyebsk'),
 (5316, 4, 'Minsk'),
 (5344, 4, 'Kyiv'),
 (5347, 4, 'Aqtöbe'),
 (5348, 4, 'Mahilyow'),
 (5352, 4, 'Kherson'),
 (5373, 2, 'Rivne'),
 (5376, 1, 'Turku'),
 (5377, 1, 'Tallinn'),
 (5384, 2, 'Minsk'),
 (5408, 2, 'Qaskeleng'),
 (5434, 4, 'Shakhtīnsk'),
 (5437, 2, 'Kremenchuk'),
 (5479, 4, 'Almaty'),
 (5484, 4, 'Baku'),
 (5488, 1, 'Hrodna'),
 (5505, 2, 'Zolotonosha'),
 (5506, 2, 'Pielavesi'),
 (5515, 0, 'Minsk'),
 (5532, 1, 'Kryvyi Rih'),
 (5540, 2, 'Taraz'),
 (5553, 2, 'Antalya'),
 (5563, 4, 'Kyiv'),
 (5565, 2, 'Seinäjoki'),
 (5570, 4, 'Vinnytsia'),
 (5592, 2, 'Yevpatoriia'),
 (5622, 4, 'Nur-Sultan'),
 (5629, 1, 'Mariupol'),
 (5640, 2, 'Kharkiv'),
 (5666, 3, 'Minsk'),
 (5675, 4, 'Şirvan'),
 (5690, 4, 'Astara'),
 (5698, 2, 'Minsk'),
 (5708, 2, 'Almaty'),
 (5721, 4, 'Nur-Sultan'),
 (5724, 1, 'Shymkent'),
 (5726, 4, 'Pastavy'),
 (5731, 1, 'Piatykhatky'),
 (5739, 1, 'Orsha'),
 (5758, 2, 'Minsk'),
 (5760, 2, 'Trabzon'),
 (5763, 1, 'Shymkent'),
 (5787, 1, 'Oulainen'),
 (5800, 1, 'Donetsk'),
 (5817, 2, 'Çorum'),
 (5821, 4, 'Vilyeyka'),
 (5822, 2, 'Qaraghandy'),
 (5825, 2, 'Vinnytsia'),
 (5867, 0, 'Minsk'),
 (5870, 2, 'Tampere'),
 (5872, 2, 'Ankara'),
 (5873, 4, 'Smila'),
 (5887, 2, 'Minsk'),
 (5888, 2, 'Balqash'),
 (5903, 4, 'Babruysk'),
 (5907, 2, 'Şanlıurfa'),
 (5927, 1, 'Inkerman'),
 (5929, 1, 'Oral'),
 (5946, 1, 'Horad Barysaw'),
 (5947, 4, 'Zhezqazghan'),
 (5958, 1, 'Gəncə'),
 (5971, 4, 'Odesa'),
 (5973, 2, 'Avdiivka'),
 (5990, 4, 'Vyshneve'),
 (5996, 1, 'Talghar'),
 (5999, 1, 'Baku'),
 (6040, 1, 'Kherson'),
 (6068, 1, 'Hora'),
 (6072, 2, 'Vitsyebsk'),
 (6099, 2, 'Svyetlahorsk'),
 (6120, 2, 'Zelenodolsk'),
 (6140, 1, 'Almaty'),
 (6147, 2, 'Dnipro'),
 (6159, 4, 'Alchevsk'),
 (6174, 4, 'Eskişehir'),
 (6176, 1, 'Qarataū'),
 (6190, 2, 'Bursa'),
 (6195, 1, 'Rudnyy'),
 (6207, 1, 'Istanbul'),
 (6245, 4, 'Kobeliaky'),
 (6246, 4, 'Berehove'),
 (6278, 1, 'Caslano'),
 (6286, 4, 'Almaty'),
 (6288, 2, 'Esik'),
 (6290, 4, 'Bern'),
 (6298, 4, 'Almaty'),
 (6320, 1, 'Baku'),
 (6335, 2, 'Kolomyia'),
 (6344, 2, 'Baku'),
 (6352, 1, 'Kayseri'),
 (6360, 4, 'Baku'),
 (6363, 4, 'Simferopol'),
 (6374, 4, 'Yevpatoriia'),
 (6378, 4, 'Khartsyzk'),
 (6423, 4, 'Baku'),
 (6431, 2, 'Şəki'),
 (6432, 4, 'Hämeenlinna'),
 (6434, 1, 'Donetsk'),
 (6484, 1, 'Zaporizhzhia'),
 (6489, 4, 'Shymkent'),
 (6496, 1, 'Vitsyebsk'),
 (6499, 1, 'Haradok'),
 (6502, 2, 'Mariupol'),
 (6505, 1, 'Rivne'),
 (6511, 2, 'Donetsk'),
 (6520, 4, 'Kherson'),
 (6522, 1, 'Haradok'),
 (6526, 4, 'Tampere'),
 (6545, 4, 'Temirtaū'),
 (6556, 1, 'Bursa'),
 (6561, 1, 'Kamianske'),
 (6568, 4, 'Antalya'),
 (6573, 2, 'Lutsk'),
 (6602, 4, 'Yevpatoriia'),
 (6603, 2, 'Kentaū'),
 (6626, 4, 'Helsinki'),
 (6642, 2, 'Kayseri'),
 (6648, 1, 'Makiivka'),
 (6649, 4, 'Myrnohrad'),
 (6652, 2, 'Denizli'),
 (6656, 4, 'Baku'),
 (6660, 4, 'Kobeliaky'),
 (6680, 2, 'Naxçıvan'),
 (6704, 2, 'Kharkiv'),
 (6706, 1, 'Almaty'),
 (6749, 4, 'Baku'),
 (6773, 4, 'Lökbatan'),
 (6777, 2, 'Sumqayıt'),
 (6804, 1, 'Juuka'),
 (6808, 1, 'Novopoltavka'),
 (6812, 2, 'Kahramanmaraş'),
 (6820, 1, 'Klichaw'),
 (6821, 4, 'Olenivka'),
 (6829, 2, 'Chernihiv'),
 (6831, 4, 'İzmir'),
 (6833, 4, 'Kharkiv'),
 (6854, 1, 'Dnipro'),
 (6858, 1, 'Yavoriv'),
 (6870, 2, 'Nikopol'),
 (6874, 4, 'Culfa'),
 (6878, 4, 'Tokat'),
 (6889, 4, 'Almaty'),
 (6893, 2, 'Jalasjärvi'),
 (6909, 4, 'Raseborg'),
 (6921, 4, 'Kangasala'),
 (6928, 4, 'Mut'),
 (6929, 2, 'Helsinki'),
 (6951, 1, 'Xaçmaz'),
 (6952, 3, 'Minsk'),
 (6955, 4, 'Makiivka'),
 (6966, 1, 'Adana'),
 (6983, 4, 'Pokrov'),
 (6991, 1, 'Petropavl'),
 (7008, 4, 'Sloviansk'),
 (7010, 1, 'Ratne'),
 (7014, 2, 'Homyel’'),
 (7037, 4, 'Kalinkavichy'),
 (7040, 2, 'Mahilyow'),
 (7042, 4, 'Aradíppou'),
 (7065, 2, 'Shakhtarsk'),
 (7088, 2, 'Horki'),
 (7146, 4, 'Konotop'),
 (7166, 4, 'Chornomorsk'),
 (7177, 4, 'Mazyr'),
 (7198, 2, 'Pavlohrad'),
 (7223, 1, 'Kryvyi Rih'),
 (7225, 4, 'Minsk'),
 (7240, 4, 'Mykolaiv'),
 (7257, 2, 'Vasylivka'),
 (7258, 2, 'Pervomaiskyi'),
 (7288, 4, 'Mykolaiv'),
 (7293, 2, 'Aqtöbe'),
 (7299, 1, 'Sudak'),
 (7325, 0, 'Minsk'),
 (7355, 2, 'Gaziantep'),
 (7374, 4, 'Lənkəran'),
 (7376, 1, 'Kalmiuske'),
 (7381, 4, 'Kozlu'),
 (7393, 1, 'Slavutych'),
 (7405, 0, 'Minsk'),
 (7407, 4, 'Drohobych'),
 (7437, 1, 'Alavus'),
 (7449, 4, 'Kryvyi Rih'),
 (7463, 4, 'Bucha'),
 (7480, 4, 'Minsk'),
 (7497, 4, 'Mariupol'),
 (7505, 2, 'Horlivka'),
 (7508, 2, 'Osmanpaşa'),
 (7512, 2, 'Adana'),
 (7517, 4, 'Yasinia'),
 (7518, 4, 'Vinnytsia'),
 (7546, 2, 'Nur-Sultan'),
 (7547, 4, 'Mykolaiv'),
 (7576, 1, 'Kyiv'),
 (7579, 2, 'Ternopil'),
 (7582, 1, 'Pokrovsk'),
 (7597, 1, 'Kyiv'),
 (7619, 1, 'Qaraghandy'),
 (7627, 2, 'Odesa'),
 (7645, 2, 'Cherkasy'),
 (7650, 2, 'Sivas'),
 (7660, 1, 'Donetsk'),
 (7679, 1, 'Aqtöbe'),
 (7695, 3, 'Minsk'),
 (7705, 4, 'Makiivka'),
 (7713, 1, 'Baku'),
 (7725, 2, 'Shymkent'),
 (7734, 4, 'Beyləqan'),
 (7753, 1, 'Kryvyi Rih'),
 (7763, 4, 'Slatyne'),
 (7766, 1, 'Kremenchuk'),
 (7783, 1, 'Limassol'),
 (7818, 2, 'Jyväskylä'),
 (7821, 4, 'Minsk'),
 (7825, 1, 'Krupki'),
 (7828, 4, 'Velyka Andrusivka'),
 (7832, 2, 'Davyd-Haradok'),
 (7834, 4, 'Babruysk'),
 (7843, 4, 'Raisio'),
 (7845, 1, 'Poltava'),
 (7878, 2, 'Shymkent'),
 (7889, 4, 'Luninyets'),
 (7894, 2, 'Heinola'),
 (7895, 1, 'Mykolaiv'),
 (7903, 4, 'Slonim'),
 (7908, 4, 'Kremenchuk'),
 (7912, 4, 'Ternopil'),
 (7929, 1, 'Baranavichy'),
 (7930, 4, 'Almaty'),
 (7935, 2, 'Dnipro'),
 (7955, 2, 'Ahrarne'),
 (7957, 2, 'Salihorsk'),
 (7963, 4, 'Qaraçuxur'),
 (7986, 1, 'Kushuhum'),
 (7987, 2, 'Uurainen'),
 (8012, 1, 'Kyiv'),
 (8044, 2, 'Kyiv'),
 (8048, 4, 'Istanbul'),
 (8072, 4, 'Balyqshy'),
 (8085, 4, 'Minsk'),
 (8089, 4, 'Ternivka'),
 (8103, 1, 'Kyiv'),
 (8149, 4, 'Baranavichy'),
 (8171, 2, 'Əmircan'),
 (8193, 4, 'Kyiv'),
 (8205, 2, 'Minsk'),
 (8208, 2, 'Ternopil'),
 (8213, 2, 'Minsk'),
 (8214, 1, 'Haisyn'),
 (8215, 2, 'Chernivtsi'),
 (8220, 2, 'Kakhovka'),
 (8233, 2, 'Horlivka'),
 (8269, 2, 'Oral'),
 (8291, 4, 'Odesa'),
 (8299, 3, 'Minsk'),
 (8305, 4, 'Brest'),
 (8313, 1, 'Ivano-Frankivsk'),
 (8325, 1, 'Ukrainka'),
 (8328, 2, 'Istanbul'),
 (8376, 4, 'Oulu'),
 (8398, 4, 'Lutsk'),
 (8399, 4, 'Espoo'),
 (8437, 4, 'Diyarbakır'),
 (8474, 4, 'Qyzylorda'),
 (8487, 1, 'Istanbul'),
 (8499, 1, 'Trabzon'),
 (8521, 1, 'Semey'),
 (8536, 2, 'Baku'),
 (8570, 4, 'Shū'),
 (8574, 2, 'Minsk'),
 (8581, 4, 'Pereshchepyne'),
 (8592, 2, 'Minsk'),
 (8609, 0, 'Minsk'),
 (8638, 2, 'Vantaa'),
 (8649, 2, 'Luhyny'),
 (8656, 4, 'Poltava'),
 (8664, 1, 'Rivne'),
 (8681, 4, 'Baku'),
 (8683, 1, 'Baku'),
 (8700, 4, 'Forssa'),
 (8715, 2, 'Minsk'),
 (8720, 4, 'Rivne'),
 (8726, 1, 'Slutsk'),
 (8745, 4, 'Donetsk'),
 (8812, 2, 'Kirkkonummi'),
 (8829, 4, 'Vilyeyka'),
 (8835, 2, 'Baku'),
 (8836, 2, 'Istanbul'),
 (8849, 2, 'Lutsk'),
 (8854, 4, 'Minsk'),
 (8875, 1, 'Kyiv'),
 (8887, 4, 'Riga'),
 (8893, 2, 'Zharkent'),
 (8992, 2, 'Shymkent'),
 (8998, 1, 'Kankaanpää'),
 (9019, 2, 'Berezivka'),
 (9048, 4, 'Kovel'),
 (9058, 4, 'Baku'),
 (9059, 4, 'Sumy'),
 (9060, 1, 'Irpin'),
 (9081, 1, 'Cəlilabad'),
 (9090, 1, 'Ivankiv'),
 (9092, 1, 'Kyiv'),
 (9114, 2, 'Zolochiv'),
 (9123, 0, 'Minsk'),
 (9140, 2, 'Horad Barysaw'),
 (9178, 1, 'Mersin'),
 (9184, 1, 'Qəzyan'),
 (9210, 4, 'Kryvyi Rih'),
 (9225, 2, 'Ankara'),
 (9258, 4, 'Zhitiqara'),
 (9268, 4, 'Istanbul'),
 (9284, 2, 'Aqtaū'),
 (9290, 1, 'Homyel’'),
 (9292, 4, 'Jyväskylän Maalaiskunta'),
 (9295, 4, 'Babruysk'),
 (9298, 2, 'Kalanchak'),
 (9320, 1, 'Vantaa'),
 (9326, 4, 'Atbasar'),
 (9331, 2, 'Navahrudak'),
 (9378, 1, 'Rovaniemi'),
 (9411, 1, 'Vuisternens-devant-Romont'),
 (9413, 3, 'Minsk'),
 (9420, 2, 'Turku'),
 (9423, 1, 'Kyiv'),
 (9441, 4, 'Cherkasy'),
 (9458, 4, 'Rovenky'),
 (9459, 1, 'Kiviõli'),
 (9467, 2, 'Mäntsälä'),
 (9513, 4, 'Aqtöbe'),
 (9526, 4, 'Kyiv'),
 (9573, 1, 'Espoo'),
 (9584, 4, 'Khrustalnyi'),
 (9591, 1, 'Kryvyi Rih'),
 (9592, 1, 'Nemyriv'),
 (9594, 2, 'Ternopil'),
 (9595, 2, 'Rivne'),
 (9609, 1, 'Nur-Sultan'),
 (9621, 1, 'Tarsus'),
 (9627, 2, 'Xırdalan'),
 (9634, 1, 'Şanlıurfa'),
 (9642, 4, 'Baku'),
 (9662, 2, 'Minsk'),
 (9671, 1, 'Minsk'),
 (9677, 4, 'Dnipro'),
 (9694, 2, 'Mahilyow'),
 (9709, 2, 'Minsk'),
 (9723, 4, 'Minsk'),
 (9726, 0, 'Minsk'),
 (9732, 4, 'Horad Barysaw'),
 (9741, 2, 'Jämsä'),
 (9768, 2, 'Aqtöbe'),
 (9775, 2, 'Homyel’'),
 (9788, 4, 'Minsk'),
 (9797, 1, 'Pinsk'),
 (9800, 4, 'Maladzyechna'),
 (9803, 4, 'Gaziantep'),
 (9825, 4, 'Inari'),
 (9842, 4, 'Brest'),
 (9852, 4, 'Almaty'),
 (9857, 4, 'Tekeli'),
 (9861, 4, 'Baku'),
 (9885, 4, 'Baku'),
 (9898, 1, 'Shymkent'),
 (9899, 1, 'Balqash'),
 (9912, 4, 'Vasylkiv'),
 (9934, 4, 'Uzda'),
 (9972, 1, 'Kökshetaū'),
 (9979, 1, 'Dnipro'),
 (9980, 4, 'Svyetlahorsk'),
 (10014, 4, 'Zaporizhzhia'),
 (10026, 4, 'Lahti'),
 (10029, 4, 'Baranavichy'),
 (10047, 2, 'Almaty'),
 (10066, 4, 'Minsk'),
 (10069, 4, 'Novoyavorovskoye'),
 (10076, 1, 'Sofiyivs’ka Borshchahivka'),
 (10081, 2, 'Petropavl'),
 (10087, 2, 'Vaasa'),
 (10115, 2, 'Keminmaa'),
 (10116, 1, 'Nizhyn'),
 (10125, 2, 'Kovel'),
 (10132, 0, 'Minsk'),
 (10140, 2, 'Navapolatsk'),
 (10142, 1, 'Eskişehir'),
 (10143, 2, 'Almaty'),
 (10170, 2, 'Limassol'),
 (10171, 4, 'Kyiv'),
 (10173, 4, 'Zhytomyr'),
 (10180, 4, 'Pokrovsk'),
 (10185, 4, 'Pudasjärvi'),
 (10199, 4, 'Simferopol'),
 (10230, 4, 'Odesa'),
 (10239, 2, 'Uzhhorod'),
 (10271, 1, 'Perevalsk'),
 (10274, 4, 'Baku'),
 (10302, 2, 'Dolynska'),
 (10311, 4, 'Baranavichy'),
 (10322, 2, 'Nizhyn'),
 (10324, 1, 'Novyi Rozdil'),
 (10327, 1, 'Mahilyow'),
 (10342, 2, 'Lökbatan'),
 (10348, 4, 'Kyiv'),
 (10397, 2, 'Oleksiivka'),
 (10414, 2, 'Almaty'),
 (10421, 1, 'Vitsyebsk'),
 (10422, 1, 'Zharkent'),
 (10437, 2, 'Porvoo'),
 (10452, 2, 'Kharkiv'),
 (10457, 2, 'Mariupol'),
 (10467, 4, 'Zaqatala'),
 (10475, 2, 'Brianka'),
 (10487, 1, 'Mykolaiv'),
 (10498, 1, 'Shymkent'),
 (10513, 4, 'Shymkent'),
 (10515, 4, 'Adana'),
 (10520, 1, 'Taraz'),
 (10544, 1, 'Vinnytsia'),
 (10545, 2, 'Jyväskylä'),
 (10547, 1, 'Minsk'),
 (10569, 2, 'Bilokurakyne'),
 (10574, 4, 'Shymkent'),
 (10579, 1, 'Dnipro'),
 (10580, 1, 'Tartu'),
 (10587, 1, 'Nikopol'),
 (10595, 4, 'Mohyliv-Podilskyi'),
 (10599, 4, 'Minsk'),
 (10637, 4, 'İzmir'),
 (10656, 2, 'Novoyavorovskoye'),
 (10659, 4, 'İzmir'),
 (10666, 2, 'Khrestivka'),
 (10683, 4, 'Kyiv'),
 (10697, 4, 'Arys'),
 (10708, 4, 'Malyn'),
 (10718, 1, 'Homyel’'),
 (10720, 1, 'Yuzhne'),
 (10723, 1, 'Kyiv'),
 (10724, 2, 'Espoo'),
 (10745, 2, 'Donetsk'),
 (10760, 4, 'Taldyqorghan'),
 (10761, 4, 'Hamina'),
 (10790, 1, 'Kryvyi Rih'),
 (10794, 4, 'Donetsk'),
 (10806, 1, 'Odesa'),
 (10823, 2, 'Simferopol'),
 (10830, 4, 'Hubynykha'),
 (10864, 2, 'Kuhmo'),
 (10867, 3, 'Minsk'),
 (10879, 1, 'Oral'),
 (10895, 2, 'Minsk'),
 (10926, 4, 'Almaty'),
 (10938, 1, 'Mingəçevir'),
 (10942, 2, 'Almaty'),
 (10943, 4, 'Nur-Sultan'),
 (10951, 2, 'Nurmes'),
 (10963, 4, 'Sniatyn'),
 (10969, 2, 'Nur-Sultan'),
 (11000, 4, 'Baku'),
 (11010, 4, 'Toretsk'),
 (11071, 4, 'Hrodna'),
 (11089, 1, 'Kyiv'),
 (11105, 1, 'Khotyn'),
 (11145, 4, 'Orsha'),
 (11151, 2, 'Minsk'),

In [9]:
cursor.execute('''
SELECT ROUND(AVG(age), 2)
FROM "user"
WHERE country = 'Cyprus';
''')

results = cursor.fetchall()
results

# cursor.close()
# connection.close()

[(Decimal('28.07'),)]

In [10]:
df = pd.read_sql(
'''
    SELECT
        exp_group, 
        os, 
        COUNT("user") AS total_users, 
        MAX(age) AS max_age, 
        MIN(age) AS min_age
    FROM "user"
    GROUP BY
        exp_group, os
''',
    con=con_url
)

df.to_csv('groupby1.csv', sep=',', index=False)

In [11]:
df = pd.read_sql(
'''
    SELECT topic, MAX(LENGTH(text)) AS max_len
    FROM post
    GROUP BY topic
''',
    con=con_url
)
df

           topic  max_len
0           tech    16063
1          covid      148
2          movie    10234
3  entertainment    19004
4       politics    25392
5          sport     9438
6       business     5378

In [12]:
df = pd.read_sql(
'''
    SELECT country, COUNT(*) as user_count
    FROM "user"
    GROUP BY country
    HAVING COUNT(*) > 1000
    ORDER BY user_count
''',    
    con=con_url
)
df

      country  user_count
0  Azerbaijan        1542
1     Finland        1599
2      Turkey        1606
3  Kazakhstan        3172
4     Belarus        3293
5     Ukraine        8273
6      Russia      143035

In [13]:
df = pd.read_sql(
'''
    SELECT country, exp_group, COUNT(id)
    FROM "user"
    GROUP BY country, exp_group;
''',    
    con=con_url
)
df

        country  exp_group  count
0    Azerbaijan          0    341
1    Azerbaijan          1    271
2    Azerbaijan          2    327
3    Azerbaijan          3    308
4    Azerbaijan          4    295
5       Belarus          0    671
6       Belarus          1    658
7       Belarus          2    644
8       Belarus          3    641
9       Belarus          4    679
10       Cyprus          0     25
11       Cyprus          1     34
12       Cyprus          2     33
13       Cyprus          3     43
14       Cyprus          4     35
15      Estonia          0     45
16      Estonia          1     40
17      Estonia          2     35
18      Estonia          3     36
19      Estonia          4     22
20      Finland          0    319
21      Finland          1    326
22      Finland          2    333
23      Finland          3    298
24      Finland          4    323
25   Kazakhstan          0    630
26   Kazakhstan          1    653
27   Kazakhstan          2    601
28   Kazakhstan          3    650
29   Kazakhstan          4    638
30       Latvia          0     39
31       Latvia          1     30
32       Latvia          2     34
33       Latvia          3     37
34       Latvia          4     35
35       Russia          0  28681
36       Russia          1  28619
37       Russia          2  28627
38       Russia          3  28711
39       Russia          4  28397
40  Switzerland          0     35
41  Switzerland          1     27
42  Switzerland          2     34
43  Switzerland          3     34
44  Switzerland          4     32
45       Turkey          0    328
46       Turkey          1    316
47       Turkey          2    314
48       Turkey          3    333
49       Turkey          4    315
50      Ukraine          0   1609
51      Ukraine          1   1664
52      Ukraine          2   1632
53      Ukraine          3   1677
54      Ukraine          4   1691

In [14]:
df = pd.read_sql(
'''
    SELECT exp_group, COUNT(id)
    FROM "user"
    WHERE city = 'Moscow'
    GROUP BY exp_group
    HAVING AVG(age) > 27.2
''',    
    con=con_url
)
df

   exp_group  count
0          1   4414
1          3   4378

In [15]:
df = pd.read_sql(
'''
    SELECT topic, COUNT(id)
    FROM post
    GROUP BY topic
    ORDER BY COUNT(id) DESC
''',    
    con=con_url
)
df

           topic  count
0          movie   3000
1          covid   1799
2       business    510
3          sport    510
4       politics    417
5           tech    401
6  entertainment    386

In [16]:
df = pd.read_sql(
'''
    SELECT id, age, exp_group
    FROM "user"
    WHERE city = 'Voronezh'
    ORDER BY age DESC, exp_group
''',    
    con=con_url
)
df

          id  age  exp_group
0      89990   71          0
1       2441   71          3
2      14184   66          3
3      35093   65          0
4      77284   64          4
...      ...  ...        ...
1369  151841   14          4
1370  116446   14          4
1371   18278   14          4
1372  110611   14          4
1373   29604   14          4

[1374 rows x 3 columns]

In [17]:
df = pd.read_sql(
'''
    SELECT * FROM "user"
    LIMIT 10
''',    
    con=con_url
)
df

    id  gender  age country               city  exp_group       os source
0  200       1   34  Russia          Degtyarsk          3  Android    ads
1  201       0   37  Russia             Abakan          0  Android    ads
2  202       1   17  Russia           Smolensk          4  Android    ads
3  203       0   18  Russia             Moscow          1      iOS    ads
4  204       0   36  Russia  Anzhero-Sudzhensk          3  Android    ads
5  205       0   32  Russia         Dugulubgey          3  Android    ads
6  206       1   20  Russia            Kamenka          1  Android    ads
7  207       1   27  Russia            Groznyy          3      iOS    ads
8  208       1   17  Russia               Zima          1  Android    ads
9  209       0   17  Russia       Yuzhnouralsk          1  Android    ads

In [18]:
df = pd.read_sql(
'''
    SELECT * FROM post
    LIMIT 10
''',    
    con=con_url
)
df

     id                                               text     topic
0     1  UK economy facing major risks\n\nThe UK manufa...  business
1     2  Aids and climate top Davos agenda\n\nClimate c...  business
2     3  Asian quake hits European shares\n\nShares in ...  business
3     4  India power shares jump on debut\n\nShares in ...  business
4     5  Lacroix label bought by US firm\n\nLuxury good...  business
5     6  Insurance bosses plead guilty\n\nAnother three...  business
6    14  Saudi investor picks up the Savoy\n\nLondons f...  business
7  2366  RACV | Annual cost of owning and maintaining a...     covid
8     7  Turkey-Iran mobile deal at risk\n\nTurkeys inv...  business
9     8  Parmalat to return to stockmarket\n\nParmalat,...  business

In [19]:
df = pd.read_sql(
'''
    SELECT * FROM feed_action
    LIMIT 10
''',    
    con=con_url
)
df

   user_id  post_id action                time        id
0    87074     6475   view 2022-01-15 19:04:38  42009857
1    95394     6413   like 2022-01-15 19:04:38  42009858
2    95394     6337   like 2022-01-15 19:04:38  42009859
3    89590     6316   view 2022-01-15 19:04:38  42009860
4     4319     6349   view 2022-01-15 19:04:38  42009861
5    95064     6317   view 2022-01-15 19:04:39  42009862
6   136060     6439   view 2022-01-15 19:04:39  42009863
7   156747     6344   view 2022-01-15 19:04:39  42009864
8   110821     6401   view 2022-01-15 19:04:39  42009865
9    40626     6476   like 2022-01-15 19:04:39  42009866

In [20]:
df = pd.read_sql(
'''
    SELECT f.post_id, f.time, u.age, u.os
    FROM feed_action f
    JOIN "user" u on f.user_id = u.id
    WHERE f.action = 'like' AND u.city = 'Omsk'
    ORDER BY f.time DESC
    LIMIT 100
''',    
    con=con_url
).to_csv('join1.csv', sep=',', index=False)
df

In [21]:
df = pd.read_sql(
'''
    SELECT u.city, COUNT (f.action) AS views 
    FROM "user" u
    JOIN feed_action f on f.user_id = u.id
    JOIN post p on f.post_id = p.id
    WHERE u.age = 36
        AND f.action = 'view'
        AND p.topic = 'covid'
        AND f.time::date = '2021-12-01'
    GROUP BY u.city
    ORDER BY views
''',    
    con=con_url
)

df

                 city  views
0         Arkhangelsk      5
1          Apsheronsk      8
2            Fryazino      8
3               Varna      9
4          Karmaskaly      9
..                ...    ...
163  Nizhniy Novgorod    126
164          Belgorod    150
165       Novosibirsk    171
166  Saint Petersburg    230
167            Moscow   1617

[168 rows x 2 columns]

In [ ]:
df = pd.read_sql(
'''
    SELECT 
        post_id,
        COUNT(*) AS likes, 
        COUNT(DISTINCT user_id) AS unique_liked_users, 
        MAX(time) AS last_like_time
    FROM feed_action
    WHERE action = 'like'
    GROUP BY post_id
    ORDER BY likes DESC
    LIMIT 20
''',    
    con=con_url
)

df

    post_id  likes  unique_liked_users      last_like_time
0      4866  31714               31714 2022-01-01 13:57:43
1      5127  29637               29637 2022-01-05 13:52:17
2      6448  27939               27939 2022-01-22 05:50:39
3      6498  27729               27729 2022-01-22 21:45:11
4      6513  27686               27686 2022-01-22 19:59:52
5      3192  26507               26251 2021-12-06 19:57:50
6      6314  26478               26478 2022-01-20 07:46:21
7      6864  24156               24156 2022-01-26 23:52:48
8      5413  23441               23441 2022-01-07 09:57:07
9      5165  22596               22596 2022-01-04 17:43:12
10     6318  22549               22549 2022-01-19 19:56:31
11     3795  22224               22224 2021-12-15 11:50:09
12     6388  21997               21997 2022-01-20 19:55:03
13     5387  21847               21847 2022-01-07 02:48:16
14     3246  21833               21674 2021-12-07 02:48:20
15     6957  21788               21788 2022-01-26 23:59:40
16     1930  21710               21710 2021-11-20 17:51:57
17     6273  21623               21623 2022-01-18 23:44:50
18     6728  21562               21562 2022-01-24 21:52:29
19     7085  21492               21492 2022-01-26 23:59:31